apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: k8scourse-demo
    role: backend
spec:
  template:
    metadata:
      labels:
        app: k8scourse-demo
        role: backend
    spec:
      containers:
        - name: api
          image: joellord/k8scourse-back
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASS
              value: mysql
  selector:
    matchLabels:
      role: backend
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: k8scourse-back
  labels:
    role: backend
spec:
  selector:
    role: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
